name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up pnpm
        uses: pnpm/action-setup@v6
        with:
          version: "10"
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "pnpm"
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"
          cache: "pip"
      - name: Install dependencies
        run: |
          pnpm install
          pip install -r test/bin/requirements.txt
      - name: Install KiCad 10
        run: |
          # Add KiCad PPA and install KiCad 10
          sudo add-apt-repository --yes ppa:kicad/kicad-10.0-releases
          sudo apt-get update
          sudo apt-get install --no-install-recommends --yes kicad
      - name: Run tests
        env:
          PCBNEW_PATH: /usr/lib/python3/dist-packages/pcbnew.py
        run: |
          pnpm test
